fix: swc minify bug avoidance
recruit-tech/recoil-sync-next pull request #33
Opened 2022-07-14 23:34 UTC by AkifumiSato

## Overview

Cannot restore values other than the last updated value in `examples/history-sync-json` in production build and reloading.

### cause

My guess is that it is probably a bug in the swc.

_no_minify_
<img width="654" alt="no_minify" src="https://user-images.githubusercontent.com/25711332/179118176-ac02f40d-3d99-4fba-a3c1-74acadc079cb.png">

_minify_
<img width="604" alt="minify" src="https://user-images.githubusercontent.com/25711332/179118192-c27eec1c-5e0a-44ad-9a57-91caf7d55ad0.png">

## demo
There is a possibility to delete the .next cache or else it won't work.

```sh
$ yarn build
$ cd examples/history-sync-json
$ rm -rf .next
$ yarn build
$ yarn start
```

2022-07-14 23:48 UTC, koichik requested changes
others are okay.

2022-07-14 23:48 UTC, koichik commented on src/history/useSyncHistory.ts
> +      if(!historyInfo.current) {
please `yarn lint-fix`

2022-07-14 23:53 UTC, AkifumiSato commented on src/history/useSyncHistory.ts
> +      if(!historyInfo.current) {
I fixed it.

2022-07-15 00:20 UTC, koichik requested changes
I think that we should change the `"target"` field of library's `tsconfig.json` to `"es2018"` rather than change the code.

2022-07-15 00:33 UTC, koichik approved these changes
lgtim!!!

2022-07-15 00:39 UTC, merged